version: '3.9'

services:

  redis:
    image: redis:7-alpine

  api:
    build: ./api
    ports:
      - 3000:3000
    environment:
      - CORS_ORIGIN=*
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3000
    environment:
      PORT: 80
    ports:
      - 80:80
    depends_on:
      - api

  localtunnel:
    build:
      context: .
      dockerfile: lt.Dockerfile
    command: "lt --port 80 --local-host frontend"
    depends_on:
      - frontend
